services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Gestion-App-Laravel
    volumes:
      - .:/var/www
      - ./gestion-ecole-laravel-firebase.json:/home/dev/Documents/gestion_scolaire_V2_Last/storage/firebase/firebase_reencoded.key
    networks:
      - app-network
    depends_on:
      - db
      - postgres

  webserver:
    image: nginx:latest
    container_name: Gestion-App-nginx
    ports:
      - "9005:80"  # Changé de 8844 à 8845
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: projet_Scolaire
      MYSQL_USER: ibrahima
      MYSQL_PASSWORD: Sonatel@2024
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: laravel_postgres
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  mysql_data:
  postgres_data:

networks:
  app-network: