version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
      - ./storage/app/gest-apprenant-laravel-firebase-adminsdk-iw06h-7cf3b600e8.json:/storage/firebase/app-gestion-pedagogique-firebase-adminsdk-pg06l-6570ed71c6.json
    ports:
      - "8000:8000"  # Le serveur Artisan écoutera sur ce port
    networks:
      - laravel
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql  # Nom du service MySQL
      DB_PORT: 3306
      DB_DATABASE: gest_apprenant_laravel
      DB_USERNAME: ibrahima
      DB_PASSWORD: 'Sonatel@2024'

  mysql:  # Service MySQL
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: gest_apprenant_laravel
      MYSQL_ROOT_PASSWORD: Sonatel@2024
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:  # Volume persistant pour les données MySQL
