# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Gestion-App-Laravel
    volumes:
      - .:/var/www
      - ./gestion-ecole-laravel-firebase.json:/home/dev/Documents/gestion_scolaire_V2_Last/storage/firebase/firebase_reencoded.key
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=projet_Scolaire
      - DB_USERNAME=ibrahima
      - DB_PASSWORD=Sonatel@2024
    networks:
      - app-network
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: Gestion-App-nginx
    ports:
      - "9005:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: projet_Scolaire
      MYSQL_USER: ibrahima
      MYSQL_PASSWORD: Sonatel@2024
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge